"""Tool launcher interface.

BM2 launches design tools in their own envs as subprocesses.
It never modifies tool code — only reads their output.
"""

from __future__ import annotations

import subprocess
from abc import ABC, abstractmethod
from pathlib import Path

from bm2.core.models import Campaign, ToolRunConfig


class ToolLauncher(ABC):
    """Interface for launching an external design tool."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Tool identifier matching DesignSource enum value."""

    @property
    @abstractmethod
    def env_spec(self) -> str:
        """How to activate: conda env name, venv path, or module path."""

    @abstractmethod
    def check_installed(self) -> bool:
        """Verify the tool is accessible."""

    @abstractmethod
    def prepare_config(
        self,
        campaign: Campaign,
        run_config: ToolRunConfig,
        run_dir: Path,
    ) -> dict:
        """Create tool-native config files in run_dir.

        Returns dict with paths to created config files.
        """

    @abstractmethod
    def launch(self, prepared: dict, run_dir: Path) -> subprocess.Popen:
        """Start the tool as a subprocess.

        Returns Popen for monitoring. Does NOT wait for completion.
        """

    @abstractmethod
    def is_complete(self, run_dir: Path) -> bool:
        """Check if the tool has finished by examining output files."""

    @abstractmethod
    def output_dir(self, run_dir: Path) -> Path:
        """Path to design outputs (fed to bm2-evaluator ingestion)."""

    @abstractmethod
    def parser_name(self) -> str:
        """Which bm2-evaluator ingestor to use (e.g. 'bindcraft')."""

    # ------------------------------------------------------------------
    # Concrete helpers for generating launch scripts
    # ------------------------------------------------------------------

    def _write_conda_launch_script(
        self,
        run_dir: Path,
        env_name: str,
        commands: str,
        cwd: str | Path | None = None,
        log_file: str | None = None,
        env_vars: dict[str, str] | None = None,
    ) -> Path:
        """Generate a bash script that activates a conda env and runs commands.

        Uses BM1's battle-tested conda discovery pattern. The script searches
        for conda.sh across standard install locations, activates the named env,
        and runs the provided commands.

        Args:
            run_dir: Directory to write the script in.
            env_name: Conda environment name to activate.
            commands: Shell commands to execute (may be multi-line).
            cwd: Working directory for the commands (optional).
            log_file: If set, redirect stdout+stderr to this file.
            env_vars: Extra environment variables to export.

        Returns:
            Path to the generated script.
        """
        script_path = Path(run_dir) / f"run_{self.name}.sh"

        env_exports = ""
        if env_vars:
            env_exports = "\n".join(
                f'export {k}="{v}"' for k, v in env_vars.items()
            ) + "\n"

        cwd_line = f'cd "{cwd}"\n' if cwd else ""
        redirect = f'exec > "{log_file}" 2>&1\n' if log_file else ""

        content = f"""\
#!/usr/bin/env bash
# Generated by BM2 {self.name} launcher — safe to re-run
set -euo pipefail

# Robust conda init (BM1 pattern)
set +u
_conda_found=false
for _conda_sh in \\
    "${{HOME}}/miniconda3/etc/profile.d/conda.sh" \\
    "${{HOME}}/miniforge3/etc/profile.d/conda.sh" \\
    "${{HOME}}/mambaforge/etc/profile.d/conda.sh" \\
    "${{HOME}}/BindMaster/conda/etc/profile.d/conda.sh" \\
    "${{HOME}}/anaconda3/etc/profile.d/conda.sh" \\
    "/opt/conda/etc/profile.d/conda.sh" \\
    "/opt/miniforge3/etc/profile.d/conda.sh"; do
    [[ -f "$_conda_sh" ]] && {{ source "$_conda_sh"; _conda_found=true; break; }}
done
[[ "$_conda_found" == true ]] || {{ echo "ERROR: conda not found" >&2; exit 1; }}
conda activate {env_name}
set -u

{env_exports}{redirect}{cwd_line}{commands}
"""
        script_path.write_text(content)
        script_path.chmod(0o755)
        return script_path

    def _write_venv_launch_script(
        self,
        run_dir: Path,
        venv_path: str | Path,
        commands: str,
        cwd: str | Path | None = None,
        log_file: str | None = None,
        env_vars: dict[str, str] | None = None,
    ) -> Path:
        """Generate a bash script that activates a UV/pip venv and runs commands.

        Args:
            run_dir: Directory to write the script in.
            venv_path: Path to the virtual environment root.
            commands: Shell commands to execute.
            cwd: Working directory (optional).
            log_file: If set, redirect stdout+stderr to this file.
            env_vars: Extra environment variables to export.

        Returns:
            Path to the generated script.
        """
        script_path = Path(run_dir) / f"run_{self.name}.sh"

        env_exports = ""
        if env_vars:
            env_exports = "\n".join(
                f'export {k}="{v}"' for k, v in env_vars.items()
            ) + "\n"

        cwd_line = f'cd "{cwd}"\n' if cwd else ""
        redirect = f'exec > "{log_file}" 2>&1\n' if log_file else ""

        content = f"""\
#!/usr/bin/env bash
# Generated by BM2 {self.name} launcher — safe to re-run
set -euo pipefail

source "{venv_path}/bin/activate"

{env_exports}{redirect}{cwd_line}{commands}
"""
        script_path.write_text(content)
        script_path.chmod(0o755)
        return script_path
