"""BoltzGen tool launcher.

BoltzGen uses a YAML spec to define the design task.
Output: CIF files + metrics CSVs in output directory.
Conda env: BoltzGen
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from bm2.core.models import Campaign, ToolRunConfig
from bm2.tools.base import ToolLauncher


class BoltzGenLauncher(ToolLauncher):
    """Launch BoltzGen in its conda env."""

    def __init__(
        self,
        install_dir: Path | None = None,
        conda_env: str = "BoltzGen",
    ):
        self._install_dir = Path(
            install_dir or Path.home() / "BindMaster" / "BoltzGen"
        )
        self._conda_env = conda_env

    @property
    def name(self) -> str:
        return "boltzgen"

    @property
    def env_spec(self) -> str:
        return f"conda:{self._conda_env}"

    def check_installed(self) -> bool:
        return self._install_dir.exists() and (
            self._install_dir / "src" / "boltzgen"
        ).exists()

    def prepare_config(
        self, campaign: Campaign, run_config: ToolRunConfig, run_dir: Path
    ) -> dict:
        run_dir.mkdir(parents=True, exist_ok=True)

        target = campaign.target
        lo, hi = run_config.binder_length_range
        protocol = run_config.extra_settings.get("protocol", "protein-anything")
        hotspots = run_config.hotspot_residues or (
            target.hotspot_residues if target else []
        )
        chains = target.chains if target else ["A"]

        # Build BoltzGen entities-based YAML (new format)
        lines = [
            f"# BoltzGen design spec for {campaign.name}",
            "# Generated by BM2",
            "",
            "entities:",
            "  # Designed binder chain",
            "  - protein:",
            "      id: B",
            f"      sequence: {lo}..{hi}",
            "",
            "  # Target protein",
            "  - file:",
            f'      path: "{target.pdb_path if target else ""}"',
            "      include:",
        ]

        for c in chains:
            lines.append("        - chain:")
            lines.append(f"            id: {c}")

        # Add hotspot binding if specified
        if hotspots:
            # Expand hotspots: "A37" -> "37", ranges "1-10" -> "1,2,...,10"
            binding_residues = []
            for h in hotspots:
                h_str = str(h)
                # Strip chain prefix
                stripped = h_str.lstrip("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
                if "-" in stripped:
                    # Range expansion
                    parts = stripped.split("-")
                    try:
                        start, end = int(parts[0]), int(parts[1])
                        binding_residues.extend(str(i) for i in range(start, end + 1))
                    except (ValueError, IndexError):
                        binding_residues.append(stripped)
                else:
                    binding_residues.append(stripped)

            binding_str = ",".join(binding_residues)
            lines.append("      binding_types:")
            for c in chains:
                lines.append("        - chain:")
                lines.append(f"            id: {c}")
                lines.append(f"            binding: {binding_str}")

        lines.append('      structure_groups: "all"')
        lines.append("")

        spec_path = run_dir / "spec.yaml"
        spec_path.write_text("\n".join(lines))

        return {
            "spec_yaml": spec_path,
            "protocol": protocol,
            "num_designs": run_config.num_designs,
            "budget": run_config.extra_settings.get("budget", run_config.num_designs),
        }

    def launch(self, prepared: dict, run_dir: Path) -> subprocess.Popen:
        output_dir = run_dir / "output"
        output_dir.mkdir(exist_ok=True)

        commands = (
            f"boltzgen run {prepared['spec_yaml']} "
            f"--output {output_dir} "
            f"--protocol {prepared['protocol']} "
            f"--num_designs {prepared['num_designs']} "
            f"--budget {prepared['budget']}"
        )
        script = self._write_conda_launch_script(
            run_dir=run_dir,
            env_name=self._conda_env,
            commands=commands,
            log_file=str(run_dir / "boltzgen.log"),
        )
        return subprocess.Popen(["bash", str(script)])

    def is_complete(self, run_dir: Path) -> bool:
        output = run_dir / "output"
        return output.exists() and (
            any(output.glob("*.cif"))
            or (output / "final_ranked_designs").exists()
        )

    def output_dir(self, run_dir: Path) -> Path:
        return run_dir / "output"

    def parser_name(self) -> str:
        return "boltzgen"
